# Generated by Django 6.0.6 on 2026-06-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='category',
            field=models.CharField(choices=[('fees', 'Fees'), ('clearance', 'Clearance'), ('results', 'Results'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('fees', 'Fees'), ('clearance', 'Clearance'), ('results', 'Results'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
