# Generated by Django 6.0.6 on 2026-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_pic_delete_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
